name: ci

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run: |
          git init .
          git remote add origin "https://x-access-token:${{ github.token }}@github.com/${{ github.repository }}.git"
          git fetch --depth=1 origin "${{ github.sha }}"
          git checkout FETCH_HEAD
      - name: Test
        run: |
          node --version
          npm test
